import { Watch } from "@/components/watch-card"

export const categories = ["Todos", "Rolex", "Patek Philippe", "Cartier", "Tag Heuer"]

// ── Rolex AAA+ (77 relojes) ──────────────────────────────────────────
export const rolexAAAWatches: Watch[] = [
  {
    id: "datejust-bicolor-azul-baguette-oyster",
    name: "Datejust Bicolor Azul Baguette Oyster",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/datejust-bicolor-azul-baguette-oyster",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/datejust-bicolor-azul-baguette-oyster",
    price: "$ 165.000",
  },
  {
    id: "datejust-bicolor-azul-baston-estriado",
    name: "Datejust Bicolor Azul Baston Estriado",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/datejust-bicolor-azul-baston-estriado",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/datejust-bicolor-azul-baston-estriado",
    price: "$ 165.000",
  },
  {
    id: "datejust-bicolor-champagne-baston-estriado",
    name: "Datejust Bicolor Champagne Baston Estriado",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/datejust-bicolor-champagne-baston-estriado",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/datejust-bicolor-champagne-baston-estriado",
    price: "$ 165.000",
  },
  {
    id: "datejust-bicolor-esfera-azul-romano",
    name: "Datejust Bicolor Esfera Azul Romano",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/datejust-bicolor-esfera-azul-romano",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/datejust-bicolor-esfera-azul-romano",
    price: "$ 165.000",
  },
  {
    id: "datejust-bicolor-morada-baston-estriado",
    name: "Datejust Bicolor Morada Baston Estriado",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/datejust-bicolor-morada-baston-estriado",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/datejust-bicolor-morada-baston-estriado",
    price: "$ 165.000",
  },
  {
    id: "datejust-bicolor-plateada-baston-estriado",
    name: "Datejust Bicolor Plateada Baston Estriado",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/datejust-bicolor-plateada-baston-estriado",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/datejust-bicolor-plateada-baston-estriado",
    price: "$ 165.000",
  },
  {
    id: "datejust-bicolor-plateada-baston-oyster",
    name: "Datejust Bicolor Plateada Baston Oyster",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/datejust-bicolor-plateada-baston-oyster",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/datejust-bicolor-plateada-baston-oyster",
    price: "$ 165.000",
  },
  {
    id: "datejust-bicolor-verde-baston-oyster",
    name: "Datejust Bicolor Verde Baston Oyster",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/datejust-bicolor-verde-baston-oyster",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/datejust-bicolor-verde-baston-oyster",
    price: "$ 165.000",
  },
  {
    id: "datejust-gold-azul-baston-jubilee",
    name: "Datejust Gold Azul Baston Jubilee",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/datejust-gold-azul-baston-jubilee",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/datejust-gold-azul-baston-jubilee",
    price: "$ 170.000",
  },
  {
    id: "datejust-gold-champagne-baston",
    name: "Datejust Gold Champagne Baston",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/datejust-gold-champagne-baston",
    price: "$ 170.000",
  },
  {
    id: "datejust-gold-esfera-azul-romano",
    name: "Datejust Gold Esfera Azul Romano",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/datejust-gold-esfera-azul-romano",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/datejust-gold-esfera-azul-romano",
    price: "$ 170.000",
  },
  {
    id: "datejust-gold-esfera-blanca-baston",
    name: "Datejust Gold Esfera Blanca Baston",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/datejust-gold-esfera-blanca-baston",
    price: "$ 170.000",
  },
  {
    id: "datejust-gold-esfera-blanca-v2",
    name: "Datejust Gold Esfera Blanca V2",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/datejust-gold-esfera-blanca-v2",
    price: "$ 170.000",
  },
  {
    id: "datejust-gold-morada-baston-estriado",
    name: "Datejust Gold Morada Baston Estriado",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/datejust-gold-morada-baston-estriado",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/datejust-gold-morada-baston-estriado",
    price: "$ 170.000",
  },
  {
    id: "datejust-gold-plateada-baston-estriado",
    name: "Datejust Gold Plateada Baston Estriado",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/datejust-gold-plateada-baston-estriado",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/datejust-gold-plateada-baston-estriado",
    price: "$ 170.000",
  },
  {
    id: "datejust-gold-plateada-romano-president",
    name: "Datejust Gold Plateada Romano President",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/datejust-gold-plateada-romano-president",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/datejust-gold-plateada-romano-president",
    price: "$ 170.000",
  },
  {
    id: "datejust-gold-tiffany-motivo-panal",
    name: "Datejust Gold Tiffany Motivo Panal",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/datejust-gold-tiffany-motivo-panal",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/datejust-gold-tiffany-motivo-panal",
    price: "$ 170.000",
  },
  {
    id: "datejust-gold-verde-baston-president",
    name: "Datejust Gold Verde Baston President",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/datejust-gold-verde-baston-president",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/datejust-gold-verde-baston-president",
    price: "$ 170.000",
  },
  {
    id: "datejust-steel-esfera-negra-romano",
    name: "Datejust Steel Esfera Negra Romano",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/datejust-steel-esfera-negra-romano",
    price: "$ 160.000",
  },
  {
    id: "datejust-steel-negra-baston-estriado",
    name: "Datejust Steel Negra Baston Estriado",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/datejust-steel-negra-baston-estriado",
    price: "$ 160.000",
  },
  {
    id: "datejust-steel-plateada-diamantes-jubilee",
    name: "Datejust Steel Plateada Diamantes Jubilee",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/datejust-steel-plateada-diamantes-jubilee",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/datejust-steel-plateada-diamantes-jubilee",
    price: "$ 160.000",
  },
  {
    id: "day-date-bicolor-azul-baguette-viernes",
    name: "Day Date Bicolor Azul Baguette Viernes",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-bicolor-azul-baguette-viernes",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-bicolor-azul-baguette-viernes",
    price: "$ 165.000",
  },
  {
    id: "day-date-bicolor-azul-diamantes-jubilee",
    name: "Day Date Bicolor Azul Diamantes Jubilee",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-bicolor-azul-diamantes-jubilee",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-bicolor-azul-diamantes-jubilee",
    price: "$ 165.000",
  },
  {
    id: "day-date-bicolor-azul-diamantes-oyster",
    name: "Day Date Bicolor Azul Diamantes Oyster",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-bicolor-azul-diamantes-oyster",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-bicolor-azul-diamantes-oyster",
    price: "$ 165.000",
  },
  {
    id: "day-date-bicolor-champagne-diamantes-jubilee",
    name: "Day Date Bicolor Champagne Diamantes Jubilee",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-bicolor-champagne-diamantes-jubilee",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-bicolor-champagne-diamantes-jubilee",
    price: "$ 165.000",
  },
  {
    id: "day-date-bicolor-champagne-romano",
    name: "Day Date Bicolor Champagne Romano",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-bicolor-champagne-romano",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-bicolor-champagne-romano",
    price: "$ 165.000",
  },
  {
    id: "day-date-bicolor-esfera-azul-baston",
    name: "Day Date Bicolor Esfera Azul Baston",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-bicolor-esfera-azul-baston",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-bicolor-esfera-azul-baston",
    price: "$ 165.000",
  },
  {
    id: "day-date-bicolor-esfera-azul-romano",
    name: "Day Date Bicolor Esfera Azul Romano",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-bicolor-esfera-azul-romano",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-bicolor-esfera-azul-romano",
    price: "$ 165.000",
  },
  {
    id: "day-date-bicolor-esfera-morada",
    name: "Day Date Bicolor Esfera Morada",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-bicolor-esfera-morada",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-bicolor-esfera-morada",
    price: "$ 165.000",
  },
  {
    id: "day-date-bicolor-morada-diamantes-oyster",
    name: "Day Date Bicolor Morada Diamantes Oyster",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-bicolor-morada-diamantes-oyster",
    price: "$ 165.000",
  },
  {
    id: "day-date-bicolor-negra-diamantes-smooth",
    name: "Day Date Bicolor Negra Diamantes Smooth",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-bicolor-negra-diamantes-smooth",
    price: "$ 165.000",
  },
  {
    id: "day-date-bicolor-plateada-diamantes-jubilee",
    name: "Day Date Bicolor Plateada Diamantes Jubilee",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-bicolor-plateada-diamantes-jubilee",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-bicolor-plateada-diamantes-jubilee",
    price: "$ 165.000",
  },
  {
    id: "day-date-bicolor-plateada-diamantes-oyster",
    name: "Day Date Bicolor Plateada Diamantes Oyster",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-bicolor-plateada-diamantes-oyster",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-bicolor-plateada-diamantes-oyster",
    price: "$ 165.000",
  },
  {
    id: "day-date-bicolor-tiffany-diamantes-jubilee",
    name: "Day Date Bicolor Tiffany Diamantes Jubilee",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-bicolor-tiffany-diamantes-jubilee",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-bicolor-tiffany-diamantes-jubilee",
    price: "$ 165.000",
  },
  {
    id: "day-date-bicolor-tiffany-diamantes-oyster",
    name: "Day Date Bicolor Tiffany Diamantes Oyster",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-bicolor-tiffany-diamantes-oyster",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-bicolor-tiffany-diamantes-oyster",
    price: "$ 165.000",
  },
  {
    id: "day-date-bicolor-turquesa-marmol",
    name: "Day Date Bicolor Turquesa Marmol",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-bicolor-turquesa-marmol",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-bicolor-turquesa-marmol",
    price: "$ 165.000",
  },
  {
    id: "day-date-bicolor-verde-diamantes-jubilee",
    name: "Day Date Bicolor Verde Diamantes Jubilee",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-bicolor-verde-diamantes-jubilee",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-bicolor-verde-diamantes-jubilee",
    price: "$ 165.000",
  },
  {
    id: "day-date-bicolor-verde-menta",
    name: "Day Date Bicolor Verde Menta",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-bicolor-verde-menta",
    price: "$ 165.000",
  },
  {
    id: "day-date-gold-azul-diamantes-oyster",
    name: "Day Date Gold Azul Diamantes Oyster",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-gold-azul-diamantes-oyster",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-gold-azul-diamantes-oyster",
    price: "$ 170.000",
  },
  {
    id: "day-date-gold-azul-diamantes-president",
    name: "Day Date Gold Azul Diamantes President",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-gold-azul-diamantes-president",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-gold-azul-diamantes-president",
    price: "$ 170.000",
  },
  {
    id: "day-date-gold-champagne-baston",
    name: "Day Date Gold Champagne Baston",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-gold-champagne-baston",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-gold-champagne-baston",
    price: "$ 170.000",
  },
  {
    id: "day-date-gold-champagne-romano",
    name: "Day Date Gold Champagne Romano",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-gold-champagne-romano",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-gold-champagne-romano",
    price: "$ 170.000",
  },
  {
    id: "day-date-gold-esfera-morada",
    name: "Day Date Gold Esfera Morada",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-gold-esfera-morada",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-gold-esfera-morada",
    price: "$ 170.000",
  },
  {
    id: "day-date-gold-esfera-turquesa",
    name: "Day Date Gold Esfera Turquesa",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-gold-esfera-turquesa",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-gold-esfera-turquesa",
    price: "$ 170.000",
  },
  {
    id: "day-date-gold-marmol-negro",
    name: "Day Date Gold Marmol Negro",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-gold-marmol-negro",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-gold-marmol-negro",
    price: "$ 170.000",
  },
  {
    id: "day-date-gold-negra-diamantes-oversize",
    name: "Day Date Gold Negra Diamantes Oversize",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-gold-negra-diamantes-oversize",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-gold-negra-diamantes-oversize",
    price: "$ 170.000",
  },
  {
    id: "day-date-gold-negra-diamantes-president",
    name: "Day Date Gold Negra Diamantes President",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-gold-negra-diamantes-president",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-gold-negra-diamantes-president",
    price: "$ 170.000",
  },
  {
    id: "day-date-gold-plateada-romano-miercoles",
    name: "Day Date Gold Plateada Romano Miercoles",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-gold-plateada-romano-miercoles",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-gold-plateada-romano-miercoles",
    price: "$ 170.000",
  },
  {
    id: "day-date-gold-verde-diamantes-oyster",
    name: "Day Date Gold Verde Diamantes Oyster",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-gold-verde-diamantes-oyster",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-gold-verde-diamantes-oyster",
    price: "$ 170.000",
  },
  {
    id: "day-date-gold-verde-diamantes-president",
    name: "Day Date Gold Verde Diamantes President",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-gold-verde-diamantes-president",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-gold-verde-diamantes-president",
    price: "$ 170.000",
  },
  {
    id: "day-date-steel-azul-cobalt-diamantes",
    name: "Day Date Steel Azul Cobalt Diamantes",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-steel-azul-cobalt-diamantes",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-steel-azul-cobalt-diamantes",
    price: "$ 165.000",
  },
  {
    id: "day-date-steel-azul-diamantes-jubilee",
    name: "Day Date Steel Azul Diamantes Jubilee",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-steel-azul-diamantes-jubilee",
    price: "$ 165.000",
  },
  {
    id: "day-date-steel-gradiente-rojo-negro",
    name: "Day Date Steel Gradiente Rojo Negro",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-steel-gradiente-rojo-negro",
    price: "$ 165.000",
  },
  {
    id: "day-date-steel-marmol-negro",
    name: "Day Date Steel Marmol Negro",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-steel-marmol-negro",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-steel-marmol-negro",
    price: "$ 165.000",
  },
  {
    id: "day-date-steel-negra-diamantes-jubilee",
    name: "Day Date Steel Negra Diamantes Jubilee",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-steel-negra-diamantes-jubilee",
    price: "$ 165.000",
  },
  {
    id: "day-date-steel-negra-diamantes-president",
    name: "Day Date Steel Negra Diamantes President",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-steel-negra-diamantes-president",
    price: "$ 165.000",
  },
  {
    id: "day-date-steel-plateada-diamantes-jubilee",
    name: "Day Date Steel Plateada Diamantes Jubilee",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-steel-plateada-diamantes-jubilee",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-steel-plateada-diamantes-jubilee",
    price: "$ 165.000",
  },
  {
    id: "day-date-steel-plateada-diamantes-oyster",
    name: "Day Date Steel Plateada Diamantes Oyster",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-steel-plateada-diamantes-oyster",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-steel-plateada-diamantes-oyster",
    price: "$ 165.000",
  },
  {
    id: "day-date-steel-plateada-diamantes-president",
    name: "Day Date Steel Plateada Diamantes President",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-steel-plateada-diamantes-president",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-steel-plateada-diamantes-president",
    price: "$ 165.000",
  },
  {
    id: "day-date-steel-tiffany-diamantes-oyster",
    name: "Day Date Steel Tiffany Diamantes Oyster",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-steel-tiffany-diamantes-oyster",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-steel-tiffany-diamantes-oyster",
    price: "$ 165.000",
  },
  {
    id: "day-date-steel-verde-diamantes-jubilee",
    name: "Day Date Steel Verde Diamantes Jubilee",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-steel-verde-diamantes-jubilee",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-steel-verde-diamantes-jubilee",
    price: "$ 165.000",
  },
  {
    id: "gmt-master-batman-esfera-negra",
    name: "GMT Master Batman Esfera Negra",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/gmt-master-batman-esfera-negra",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/gmt-master-batman-esfera-negra",
    price: "$ 170.000",
  },
  {
    id: "gmt-master-bicolor-esfera-azul",
    name: "GMT Master Bicolor Esfera Azul",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/gmt-master-bicolor-esfera-azul",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/gmt-master-bicolor-esfera-azul",
    price: "$ 170.000",
  },
  {
    id: "gmt-master-bicolor-esfera-blanca",
    name: "GMT Master Bicolor Esfera Blanca",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/gmt-master-bicolor-esfera-blanca",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/gmt-master-bicolor-esfera-blanca",
    price: "$ 170.000",
  },
  {
    id: "gmt-master-steel-esfera-azul-total",
    name: "GMT Master Steel Esfera Azul Total",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/gmt-master-steel-esfera-azul-total",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/gmt-master-steel-esfera-azul-total",
    price: "$ 170.000",
  },
  {
    id: "gmt-master-steel-esfera-negra-blanca",
    name: "GMT Master Steel Esfera Negra Blanca",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/gmt-master-steel-esfera-negra-blanca",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/gmt-master-steel-esfera-negra-blanca",
    price: "$ 170.000",
  },
  {
    id: "sky-dweller-bicolor-negra-baston-jubilee",
    name: "Sky Dweller Bicolor Negra Baston Jubilee",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/sky-dweller-bicolor-negra-baston-jubilee",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/sky-dweller-bicolor-negra-baston-jubilee",
    price: "$ 175.000",
  },
  {
    id: "sky-dweller-bicolor-tiffany-baston",
    name: "Sky Dweller Bicolor Tiffany Baston",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/sky-dweller-bicolor-tiffany-baston",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/sky-dweller-bicolor-tiffany-baston",
    price: "$ 175.000",
  },
  {
    id: "sky-dweller-gold-azul-baston-jubilee",
    name: "Sky Dweller Gold Azul Baston Jubilee",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/sky-dweller-gold-azul-baston-jubilee",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/sky-dweller-gold-azul-baston-jubilee",
    price: "$ 175.000",
  },
  {
    id: "submariner-bicolor-esfera-azul-bicolor",
    name: "Submariner Bicolor Esfera Azul Bicolor",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/submariner-bicolor-esfera-azul-bicolor",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/submariner-bicolor-esfera-azul-bicolor",
    price: "$ 165.000",
  },
  {
    id: "submariner-steel-esfera-azul-intenso",
    name: "Submariner Steel Esfera Azul Intenso",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/submariner-steel-esfera-azul-intenso",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/submariner-steel-esfera-azul-intenso",
    price: "$ 165.000",
  },
  {
    id: "submariner-steel-esfera-azul-negro",
    name: "Submariner Steel Esfera Azul Negro",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/submariner-steel-esfera-azul-negro",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/submariner-steel-esfera-azul-negro",
    price: "$ 165.000",
  },
  {
    id: "submariner-steel-esfera-blanca-azul",
    name: "Submariner Steel Esfera Blanca Azul",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/submariner-steel-esfera-blanca-azul",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/submariner-steel-esfera-blanca-azul",
    price: "$ 165.000",
  },
  {
    id: "submariner-steel-esfera-negra-blanco",
    name: "Submariner Steel Esfera Negra Blanco",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/submariner-steel-esfera-negra-blanco",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/submariner-steel-esfera-negra-blanco",
    price: "$ 165.000",
  },
  {
    id: "submariner-steel-esfera-negra-clasica",
    name: "Submariner Steel Esfera Negra Clasica",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/submariner-steel-esfera-negra-clasica",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/submariner-steel-esfera-negra-clasica",
    price: "$ 165.000",
  },
  {
    id: "submariner-steel-esfera-verde-negro",
    name: "Submariner Steel Esfera Verde Negro",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/submariner-steel-esfera-verde-negro",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/submariner-steel-esfera-verde-negro",
    price: "$ 165.000",
  },
  {
    id: "submariner-steel-verde-hulk-clasico",
    name: "Submariner Steel Verde Hulk Clasico",
    brand: "Rolex AAA+",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/submariner-steel-verde-hulk-clasico",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/submariner-steel-verde-hulk-clasico",
    price: "$ 165.000",
  }
]

// ── Rolex AAA+ Automáticos (38 relojes) ───────────────────────────────
export const rolexAutoWatches: Watch[] = [
  {
    id: "datejust-gold-esfera-negra-rayada",
    name: "Datejust Gold Esfera Negra Rayada",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/datejust-gold-esfera-negra-rayada",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/datejust-gold-esfera-negra-rayada",
    price: "$ 200.000",
  },
  {
    id: "datejust-steel-esfera-nacar-diamantes",
    name: "Datejust Steel Esfera Nacar Diamantes",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/datejust-steel-esfera-nacar-diamantes",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/datejust-steel-esfera-nacar-diamantes",
    price: "$ 200.000",
  },
  {
    id: "datejust-steel-negro-indices-diamantes",
    name: "Datejust Steel Negro Indices Diamantes",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/datejust-steel-negro-indices-diamantes",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/datejust-steel-negro-indices-diamantes",
    price: "$ 200.000",
  },
  {
    id: "day-date-bicolor-champagne-diamantes",
    name: "Day Date Bicolor Champagne Diamantes",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-bicolor-champagne-diamantes",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-bicolor-champagne-diamantes",
    price: "$ 210.000",
  },
  {
    id: "day-date-bicolor-negra-diamantes",
    name: "Day Date Bicolor Negra Diamantes",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-bicolor-negra-diamantes",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-bicolor-negra-diamantes",
    price: "$ 210.000",
  },
  {
    id: "day-date-bicolor-plateada-diamantes",
    name: "Day Date Bicolor Plateada Diamantes",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-bicolor-plateada-diamantes",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-bicolor-plateada-diamantes",
    price: "$ 210.000",
  },
  {
    id: "day-date-gold-candy-edicion-especial",
    name: "Day Date Gold Candy Edicion Especial",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-gold-candy-edicion-especial",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-gold-candy-edicion-especial",
    price: "$ 210.000",
  },
  {
    id: "day-date-steel-candy-edicion-especial",
    name: "Day Date Steel Candy Edicion Especial",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-steel-candy-edicion-especial",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-steel-candy-edicion-especial",
    price: "$ 210.000",
  },
  {
    id: "day-date-steel-rosa-diamantes",
    name: "Day Date Steel Rosa Diamantes",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/day-date-steel-rosa-diamantes",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/day-date-steel-rosa-diamantes",
    price: "$ 210.000",
  },
  {
    id: "daytona-bicolor-esfera-blanca-crono",
    name: "Daytona Bicolor Esfera Blanca Crono",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/daytona-bicolor-esfera-blanca-crono",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/daytona-bicolor-esfera-blanca-crono",
    price: "$ 220.000",
  },
  {
    id: "daytona-gold-esfera-dorada-full",
    name: "Daytona Gold Esfera Dorada Full",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/daytona-gold-esfera-dorada-full",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/daytona-gold-esfera-dorada-full",
    price: "$ 225.000",
  },
  {
    id: "daytona-gold-rubber-esfera-champagne",
    name: "Daytona Gold Rubber Esfera Champagne",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/daytona-gold-rubber-esfera-champagne",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/daytona-gold-rubber-esfera-champagne",
    price: "$ 225.000",
  },
  {
    id: "daytona-steel-esfera-negra-blanca",
    name: "Daytona Steel Esfera Negra Blanca",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/daytona-steel-esfera-negra-blanca",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/daytona-steel-esfera-negra-blanca",
    price: "$ 220.000",
  },
  {
    id: "daytona-steel-esfera-negra-crono",
    name: "Daytona Steel Esfera Negra Crono",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/daytona-steel-esfera-negra-crono",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/daytona-steel-esfera-negra-crono",
    price: "$ 220.000",
  },
  {
    id: "daytona-steel-rubber-esfera-gris",
    name: "Daytona Steel Rubber Esfera Gris",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/daytona-steel-rubber-esfera-gris",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/daytona-steel-rubber-esfera-gris",
    price: "$ 220.000",
  },
  {
    id: "daytona-steel-rubber-esfera-negra",
    name: "Daytona Steel Rubber Esfera Negra",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/daytona-steel-rubber-esfera-negra",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/daytona-steel-rubber-esfera-negra",
    price: "$ 220.000",
  },
  {
    id: "gmt-master-bicolor-esfera-negra",
    name: "GMT Master Bicolor Esfera Negra",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/gmt-master-bicolor-esfera-negra",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/gmt-master-bicolor-esfera-negra",
    price: "$ 215.000",
  },
  {
    id: "gmt-master-coke-esfera-negra",
    name: "GMT Master Coke Esfera Negra",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/gmt-master-coke-esfera-negra",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/gmt-master-coke-esfera-negra",
    price: "$ 215.000",
  },
  {
    id: "gmt-master-gold-esfera-negra-full",
    name: "GMT Master Gold Esfera Negra Full",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/gmt-master-gold-esfera-negra-full",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/gmt-master-gold-esfera-negra-full",
    price: "$ 225.000",
  },
  {
    id: "gmt-master-pepsi-esfera-negra",
    name: "GMT Master Pepsi Esfera Negra",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/gmt-master-pepsi-esfera-negra",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/gmt-master-pepsi-esfera-negra",
    price: "$ 215.000",
  },
  {
    id: "gmt-master-pepsi-esfera-plateada",
    name: "GMT Master Pepsi Esfera Plateada",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/gmt-master-pepsi-esfera-plateada",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/gmt-master-pepsi-esfera-plateada",
    price: "$ 215.000",
  },
  {
    id: "gmt-master-steel-negro-jubilee",
    name: "GMT Master Steel Negro Jubilee",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/gmt-master-steel-negro-jubilee",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/gmt-master-steel-negro-jubilee",
    price: "$ 215.000",
  },
  {
    id: "sky-dweller-gold-champagne-baston-jubilee",
    name: "Sky Dweller Gold Champagne Baston Jubilee",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/sky-dweller-gold-champagne-baston-jubilee",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/sky-dweller-gold-champagne-baston-jubilee",
    price: "$ 230.000",
  },
  {
    id: "sky-dweller-gold-esfera-champagne",
    name: "Sky Dweller Gold Esfera Champagne",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/sky-dweller-gold-esfera-champagne",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/sky-dweller-gold-esfera-champagne",
    price: "$ 230.000",
  },
  {
    id: "sky-dweller-gold-esfera-dorada-full",
    name: "Sky Dweller Gold Esfera Dorada Full",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/sky-dweller-gold-esfera-dorada-full",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/sky-dweller-gold-esfera-dorada-full",
    price: "$ 230.000",
  },
  {
    id: "sky-dweller-gold-esfera-negra-full",
    name: "Sky Dweller Gold Esfera Negra Full",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/sky-dweller-gold-esfera-negra-full",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/sky-dweller-gold-esfera-negra-full",
    price: "$ 230.000",
  },
  {
    id: "sky-dweller-steel-esfera-negra",
    name: "Sky Dweller Steel Esfera Negra",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/sky-dweller-steel-esfera-negra",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/sky-dweller-steel-esfera-negra",
    price: "$ 220.000",
  },
  {
    id: "sky-dweller-steel-esfera-plateada",
    name: "Sky Dweller Steel Esfera Plateada",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/sky-dweller-steel-esfera-plateada",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/sky-dweller-steel-esfera-plateada",
    price: "$ 220.000",
  },
  {
    id: "sky-dweller-steel-esfera-verde",
    name: "Sky Dweller Steel Esfera Verde",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/sky-dweller-steel-esfera-verde",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/sky-dweller-steel-esfera-verde",
    price: "$ 220.000",
  },
  {
    id: "submariner-gold-esfera-negra-full",
    name: "Submariner Gold Esfera Negra Full",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/submariner-gold-esfera-negra-full",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/submariner-gold-esfera-negra-full",
    price: "$ 225.000",
  },
  {
    id: "submariner-gold-esfera-negra-plateada",
    name: "Submariner Gold Esfera Negra Plateada",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/submariner-gold-esfera-negra-plateada",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/submariner-gold-esfera-negra-plateada",
    price: "$ 225.000",
  },
  {
    id: "submariner-gold-esfera-verde-full",
    name: "Submariner Gold Esfera Verde Full",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/submariner-gold-esfera-verde-full",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/submariner-gold-esfera-verde-full",
    price: "$ 225.000",
  },
  {
    id: "submariner-gold-verde-clasico-bisel",
    name: "Submariner Gold Verde Clasico Bisel",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/submariner-gold-verde-clasico-bisel",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/submariner-gold-verde-clasico-bisel",
    price: "$ 225.000",
  },
  {
    id: "submariner-labelnoir-esfera-crema",
    name: "Submariner Labelnoir Esfera Crema",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/submariner-labelnoir-esfera-crema",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/submariner-labelnoir-esfera-crema",
    price: "$ 215.000",
  },
  {
    id: "submariner-labelnoir-esfera-negra",
    name: "Submariner Labelnoir Esfera Negra",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/submariner-labelnoir-esfera-negra",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/submariner-labelnoir-esfera-negra",
    price: "$ 215.000",
  },
  {
    id: "submariner-labelnoir-steel-clasico",
    name: "Submariner Labelnoir Steel Clasico",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/submariner-labelnoir-steel-clasico",
    price: "$ 215.000",
  },
  {
    id: "submariner-steel-esfera-negra-baston",
    name: "Submariner Steel Esfera Negra Baston",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/submariner-steel-esfera-negra-baston",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/submariner-steel-esfera-negra-baston",
    price: "$ 200.000",
  },
  {
    id: "submariner-steel-verde-hulk-ceramica",
    name: "Submariner Steel Verde Hulk Ceramica",
    brand: "Rolex AAA+ Automáticos",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/submariner-steel-verde-hulk-ceramica",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/submariner-steel-verde-hulk-ceramica",
    price: "$ 200.000",
  }
]

// ── Tag Heuer (12 relojes) ────────────────────────────────────────────
export const tagHeuerWatches: Watch[] = [
  {
    id: "carrera-steel-esfera-negra-crono",
    name: "Carrera Steel Esfera Negra Crono",
    brand: "Tag Heuer",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/relojes/fotos/carrera-steel-esfera-negra-crono.jpg",
    price: "$ 280.000",
  },
  {
    id: "carrera-steel-negra-segundero-rojo",
    name: "Carrera Steel Negra Segundero Rojo",
    brand: "Tag Heuer",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/carrera-steel-negra-segundero-rojo",
    price: "$ 280.000",
  },
  {
    id: "formula1-crono-amarilla-rubber-amarillo",
    name: "Formula 1 Crono Amarilla Rubber Amarillo",
    brand: "Tag Heuer",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/formula1-crono-amarilla-rubber-amarillo",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/formula1-crono-amarilla-rubber-amarillo",
    price: "$ 280.000",
  },
  {
    id: "formula1-crono-esfera-amarilla-steel",
    name: "Formula 1 Crono Esfera Amarilla Steel",
    brand: "Tag Heuer",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/formula1-crono-esfera-amarilla-steel",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/formula1-crono-esfera-amarilla-steel",
    price: "$ 280.000",
  },
  {
    id: "formula1-crono-esfera-naranja-steel",
    name: "Formula 1 Crono Esfera Naranja Steel",
    brand: "Tag Heuer",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/formula1-crono-esfera-naranja-steel",
    price: "$ 280.000",
  },
  {
    id: "formula1-crono-esfera-negra-tachymetre",
    name: "Formula 1 Crono Esfera Negra Tachymetre",
    brand: "Tag Heuer",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/formula1-crono-esfera-negra-tachymetre",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/formula1-crono-esfera-negra-tachymetre",
    price: "$ 280.000",
  },
  {
    id: "formula1-crono-esfera-roja-rubber",
    name: "Formula 1 Crono Esfera Roja Rubber",
    brand: "Tag Heuer",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/formula1-crono-esfera-roja-rubber",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/formula1-crono-esfera-roja-rubber",
    price: "$ 280.000",
  },
  {
    id: "formula1-crono-esfera-roja-tachymetre",
    name: "Formula 1 Crono Esfera Roja Tachymetre",
    brand: "Tag Heuer",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/formula1-crono-esfera-roja-tachymetre",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/formula1-crono-esfera-roja-tachymetre",
    price: "$ 280.000",
  },
  {
    id: "formula1-crono-verde-rubber-verde",
    name: "Formula 1 Crono Verde Rubber Verde",
    brand: "Tag Heuer",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/formula1-crono-verde-rubber-verde",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/formula1-crono-verde-rubber-verde",
    price: "$ 280.000",
  },
  {
    id: "formula1-kimi-esfera-azul-bracelet",
    name: "Formula 1 Kimi Esfera Azul Bracelet",
    brand: "Tag Heuer",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/formula1-kimi-esfera-azul-bracelet",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/formula1-kimi-esfera-azul-bracelet",
    price: "$ 280.000",
  },
  {
    id: "formula1-kimi-esfera-negra-steel",
    name: "Formula 1 Kimi Esfera Negra Steel",
    brand: "Tag Heuer",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/formula1-kimi-esfera-negra-steel",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/formula1-kimi-esfera-negra-steel",
    price: "$ 280.000",
  },
  {
    id: "formula1-steel-esfera-verde-crono",
    name: "Formula 1 Steel Esfera Verde Crono",
    brand: "Tag Heuer",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/formula1-steel-esfera-verde-crono",
    price: "$ 280.000",
  }
]

// ── Patek Philippe (7 relojes) ───────────────────────────────────────────────
const CLD = "https://res.cloudinary.com/dt1lodc8c/image/upload/w_800,c_fill,g_auto:subject,z_0.85,q_auto:best,f_auto/"

export const patekWatches: Watch[] = [
  {
    id: "patek-nautilus-acero-azul",
    name: "Nautilus Acero Azul",
    brand: "Patek Philippe",
    image: CLD + "764c8278-3d46-4473-b9b9-71ef31274288_jmfuvy.jpg",
    price: "$ 215.000",
  },
  {
    id: "patek-nautilus-gold",
    name: "Nautilus Gold",
    brand: "Patek Philippe",
    image: CLD + "8177cc18-7f9f-4c5f-b5f8-dacea15617b1_lv42zs.jpg",
    price: "$ 215.000",
  },
  {
    id: "patek-nautilus-bicolor",
    name: "Nautilus Bicolor",
    brand: "Patek Philippe",
    image: CLD + "7a5b4f08-13f6-4e1c-ba39-42159e519fed_cwc1fy.jpg",
    price: "$ 215.000",
  },
  {
    id: "patek-nautilus-acero-plateado",
    name: "Nautilus Acero Plateado",
    brand: "Patek Philippe",
    image: CLD + "b6c029ff-ad90-4d2c-adcd-78e60a95abc5_k3tldc.jpg",
    price: "$ 215.000",
  },
  {
    id: "patek-nautilus-rojo",
    name: "Nautilus Rojo",
    brand: "Patek Philippe",
    image: CLD + "79a0f9bc-773f-40a3-b1ef-cbd60154f923_ld6bsm.jpg",
    price: "$ 215.000",
  },
  {
    id: "patek-nautilus-gold-plateado",
    name: "Nautilus Gold Plateado",
    brand: "Patek Philippe",
    image: CLD + "e002b2d2-b4f7-4d36-8ceb-bb349e58ba56_in6fxk.jpg",
    price: "$ 215.000",
  },
  {
    id: "patek-nautilus-acero-azul-oscuro",
    name: "Nautilus Acero Azul Oscuro",
    brand: "Patek Philippe",
    image: CLD + "daa7cccc-53bb-4ef2-80a2-032951c2c33f_tura3x.jpg",
    price: "$ 215.000",
  },
  {
    id: "nautilus-annual-calendar-esfera-amarilla",
    name: "Nautilus Annual Calendar Esfera Amarilla",
    brand: "Patek Philippe",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/nautilus-annual-calendar-esfera-amarilla",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/nautilus-annual-calendar-esfera-amarilla",
    price: "$ 350.000",
  },
  {
    id: "nautilus-annual-calendar-esfera-negra",
    name: "Nautilus Annual Calendar Esfera Negra",
    brand: "Patek Philippe",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/nautilus-annual-calendar-esfera-negra",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/nautilus-annual-calendar-esfera-negra",
    price: "$ 350.000",
  },
  {
    id: "nautilus-annual-calendar-esfera-plateada",
    name: "Nautilus Annual Calendar Esfera Plateada",
    brand: "Patek Philippe",
    image: "https://res.cloudinary.com/dt1lodc8c/image/upload/w_700,h_700,c_fill,g_center,q_auto:best,f_auto/relojes/fotos/nautilus-annual-calendar-esfera-plateada",
    video: "https://res.cloudinary.com/dt1lodc8c/video/upload/q_auto/relojes/videos/nautilus-annual-calendar-esfera-plateada",
    price: "$ 350.000",
  },
]

// ── Cartier (2 relojes) ──────────────────────────────────────────────────────
export const cartierWatches: Watch[] = [
  {
    id: "cartier-santos-cuadrado",
    name: "Santos Cuadrado",
    brand: "Cartier",
    image: CLD + "55286ff8-16e8-4e08-b80f-97b82bdf9ac5_leuggi.jpg",
    price: "$ 225.000",
  },
  {
    id: "cartier-santos-gold-premium",
    name: "Santos Gold Premium",
    brand: "Cartier",
    image: CLD + "c0440cfa-babe-4fbd-9635-add797c5f815_mclohv.jpg",
    price: "$ 225.000",
  },
]
